Numpy
<br>
&emsp;  Data structure for adding support for large, multi-dimensional arrays and matrices

In [3]:
import numpy as np

In [11]:
# numpy is similar to list but requires only homogeneus data i.e values are of same type

a= np.array([1,2])
a[0]="t"

ValueError: invalid literal for int() with base 10: 't'

In [21]:
# Accessing a 2D Array
a= np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
print(a[1,2])
print(a[1:])
print(a[1,1:3])
print(a[1:2,1:3])

6
[[4 5 6]
 [7 8 9]]
[5 6]
[[5 6]]


In [29]:
# Broadcasting the numpy
b= np.array([1,2,3])
print(a+3)
print(a/3)
print(a+b)
print(a/b)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1.  1.  1. ]
 [4.  2.5 2. ]
 [7.  4.  3. ]]


In [34]:
# if condition can be applied to numpy
a[a%2==1]

array([1, 3, 5, 7, 9])